version: '3.7'

services:
  user_reg_web:
    container_name: wellcome
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "python /usr/django/wellcome/manage.py migrate --noinput && python /usr/django/wellcome/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/django/wellcome
    ports:
      - 8000:8000
